# Uncomment this if you want to auto-trigger on pushes to master
# trigger:
# - master

pool:
  name: Default

steps:
- script: echo Hello, it's my Azure DevOps App
  displayName: 'Run an echo command'

- script: mvn clean install
  displayName: 'Build with Maven'

- script: java -jar target/com.ng5.App-0.0.1-SNAPSHOT.jar
  displayName: 'Run the JAR file of My com.ng5.App App'
